// Core data types for Mindow

/// A single point-in-time snapshot of a process's metrics.
#[derive(Debug, Clone, PartialEq)]
pub struct ProcessSample {
    pub name: String,
    pub pid: u32,
    pub cpu_percent: f32,
    pub memory_bytes: u64,
    pub disk_read_bytes: u64,
    pub disk_write_bytes: u64,
    pub exe_path: Option<String>,
    pub start_time: u64, // Unix timestamp
    pub parent_pid: Option<u32>,
}

/// System-level metrics collected in a single cycle.
#[derive(Debug, Clone, PartialEq)]
pub struct SystemSample {
    pub total_memory: u64,
    pub used_memory: u64,
    pub per_core_cpu: Vec<f32>,
    pub battery: BatteryStatus,
}

/// Battery availability and state.
#[derive(Debug, Clone, PartialEq)]
pub enum BatteryStatus {
    Available { level: f32, charging: ChargingState },
    Unavailable,
}

/// Charging state of the battery.
#[derive(Debug, Clone, PartialEq)]
pub enum ChargingState {
    Charging,
    Discharging,
    Full,
    Unknown,
}

/// Classification of a process's executable path.
#[derive(Debug, Clone, PartialEq)]
pub enum PathStatus {
    /// System core process (C:\Windows\, WindowsApps)
    System,
    /// User-installed application
    User,
    /// No path detected (likely a system service we can't read)
    Unknown,
}

/// A filtered collection of processes after top-N selection and deduplication.
#[derive(Debug, Clone, PartialEq)]
pub struct FilteredSnapshot {
    pub processes: Vec<FilteredProcess>,
}

/// A process paired with its path classification.
#[derive(Debug, Clone, PartialEq)]
pub struct FilteredProcess {
    pub sample: ProcessSample,
    pub path_status: PathStatus,
}

/// Alerts generated by the rule engine when anomalies are detected.
#[derive(Debug, Clone, PartialEq)]
pub enum Alert {
    MemoryLeak {
        process_name: String,
        pid: u32,
        start_memory: u64,
        current_memory: u64,
        consecutive_samples: usize,
    },
    HighCpu {
        process_name: String,
        pid: u32,
        average_cpu: f32,
        duration_secs: u64,
    },
    BatteryWarning {
        battery_level: f32,
        offending_processes: Vec<BatteryOffender>,
    },
    MemoryPressure {
        used_percent: f32,
        candidates: Vec<MemoryCandidate>,
    },
}

/// A process that is draining battery through high resource usage.
#[derive(Debug, Clone, PartialEq)]
pub struct BatteryOffender {
    pub name: String,
    pub pid: u32,
    pub cpu_percent: f32,
    pub memory_bytes: u64,
}

/// A process that is a candidate for the user to close during memory pressure.
#[derive(Debug, Clone, PartialEq)]
pub struct MemoryCandidate {
    pub name: String,
    pub pid: u32,
    pub memory_bytes: u64,
}

/// Severity classification for alerts.
/// Critical (red) for system-threatening conditions; Warning (yellow) for notable conditions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AlertSeverity {
    /// Red: MemoryPressure, HighCpu
    Critical,
    /// Yellow: MemoryLeak, BatteryWarning
    Warning,
}

impl Alert {
    /// Classify the severity of this alert.
    ///
    /// Critical (red): MemoryPressure, HighCpu
    /// Warning (yellow): MemoryLeak, BatteryWarning
    pub fn severity(&self) -> AlertSeverity {
        match self {
            Alert::MemoryPressure { .. } | Alert::HighCpu { .. } => AlertSeverity::Critical,
            Alert::MemoryLeak { .. } | Alert::BatteryWarning { .. } => AlertSeverity::Warning,
        }
    }
}
